#!/bin/sh
# Start Gnome 3 Desktop 
[ -x /etc/vnc/xstartup ] && exec /etc/vnc/xstartup 
[ -r /root/.Xresources ] && xrdb /root/.Xresources 
vncconfig -iconic & 
dbus-launch --exit-with-session gnome-session &
